services:

  postgres:
    image: pgvector/pgvector:pg16
    container_name: ai-postgres

    environment:
      POSTGRES_DB: ai_kb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    restart: unless-stopped

  minio:
    image: minio/minio
    container_name: ai-minio

    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123456

    command: server /data --console-address ":9001"

    ports:
      - "9000:9000"
      - "9001:9001"

    volumes:
      - minio_data:/data

    restart: unless-stopped

volumes:
  postgres_data:
  minio_data: